services:

  classificator:
    build:
      context: .
      dockerfile: classificator/Dockerfile
    hostname: classificator
    container_name: classificator
    ports:
      - "8000:8000"
    volumes:
      - ./classificator:/home/app/classificator
      - ./common:/home/app/common
    restart: always
    depends_on:
      - ollama

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

