services:
  openai:
    build:
      context: .
      dockerfile: openai_solution/Dockerfile
    hostname: openai
    container_name: openai
    ports:
      - "8000:8000"
    volumes:
      - ./openai_solution/src:/home/app/src
      - ./common:/home/app/common