services:
  classificator:
    build:
      context: .
      dockerfile: classificator/Dockerfile
    hostname: classificator
    container_name: classificator
    ports:
      - "8000:8000"
    volumes:
      - ./classificator/src:/home/app/src
      - ./common:/home/app/common
